main:
  - name: Syllabus
    url: /syllabus/
    weight: 1
  - name: Schedule
    url: /schedule/
    weight: 2
  - name: Course material
    url: /class/
    weight: 3
  - name: References
    url: /reference/
    weight: 4
#  - name: Assignments
#    url: /assignment/
#    weight: 5
#  - name: RStudio.cloud
#    url: https://rstudio.cloud/
#    weight: 7
assignment:
  - name: Assignments
    weight: 1
  - name: Problem sets
    weight: 2
