---
title: "Day 1: Fundamentals of Deep Learning I"
# linktitle: "1. Introduction to RStudio and Images"
date: "2020-06-08"
class_date: "2020-06-08"
output:
  blogdown::html_page:
    toc: false
menu:
  class:
    parent: Class sessions
    weight: 1
type: docs
weight: 1
# pdf: 
# thumb: 
editor_options: 
  chunk_output_type: console
---

## Slides

### Class Introduction

<a href="../../slides/00_Introduction.html#1" target="_blank">Lecture slides in HTML format</a>

<a href="../../slides/00_Introduction.pdf" target="_blank">Lecture handouts in PDF format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/00_Introduction.html#1')
```

### Getting started

<a href="../../slides/00_Getting_started.html#1" target="_blank">Lecture slides in HTML format</a>

<a href="../../slides/00_Getting_started.pdf" target="_blank">Lecture handouts in PDF format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/00_Getting_started.html#1')
```

### Neural network fundamentals

<a href="../../slides/01_Neural_network.html#1" target="_blank">Lecture slides in HTML format</a>

<a href="../../slides/01_Neural_network.pdf" target="_blank">Lecture handouts in PDF format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/01_Neural_network.html#1')
```
