---
title: "Day 5: Generative Adversarial Networks, Autoencoders, Recurrent Neural Networks, LSTM, GRU, sequence learning"
# linktitle: "1. Introduction to RStudio and Images"
date: "2020-06-12"
class_date: "2020-06-12"
output:
  blogdown::html_page:
    toc: false
menu:
  class:
    parent: Class sessions
    weight: 5
type: docs
weight: 1
# pdf: 
# thumb: 
editor_options: 
  chunk_output_type: console
---


## Slides

### Recurrent Neural Networks, LSTM, GRU, sequence learning

<a href="../../slides/30_RNN.html#1" target="_blank">Lecture slides in HTML format</a>

<a href="../../slides/30_RNN.pdf" target="_blank">Lecture handouts in PDF format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/30_RNN.html#1')
```

### Generative Adversarial Networks, Autoencoders

<a href="../../slides/31_GAN.html#1" target="_blank">Lecture slides in HTML format</a>

<a href="../../slides/31_GAN.pdf" target="_blank">Lecture handouts in PDF format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/31_GAN.html#1')
```
